ratings:
  namespace: opsta-dev
  image: bigdev2000/ratings
  tag: dev
  replicas: 1
  imagePullSecrets: default-token-r2ttf
  port: 8080
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-dev-ratings-mongodb-secret
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: ratings.dev.big-bookinfo.opsta.in.th
  path: "/ais/ratings(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-dev-ratings-mongodb:27017/ratings-dev
  MONGO_DB_USERNAME: ratings-dev
  COMMIT_ID: CHANGE_ME